name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions:
  contents: read
  # Add this permission to allow status checks
  statuses: write
  # Add this permission to allow PR comments/annotations
  pull-requests: write

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # Add these permissions at job level
      statuses: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@4e8a7c2bf106c4c766c816b35ec612638dc9b6b2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Disable JavaScript Standard linter
          VALIDATE_JAVASCRIPT_STANDARD: false
          # Enable Prettier instead
          VALIDATE_PRETTIER: true
          # Optionally add ESLint for additional checks
          VALIDATE_JAVASCRIPT_ES: true
          # Specify default linter for JavaScript files
          JAVASCRIPT_DEFAULT_STYLE: "prettier"
